{
  "headers": {
    "host": "localhost:8081",
    "connection": "keep-alive",
    "content-length": "86",
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"96\", \"Google Chrome\";v=\"96\"",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "sec-ch-ua-mobile": "?0",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36",
    "sec-ch-ua-platform": "\"Windows\"",
    "postman-token": "9306be84-cac0-c3bc-6370-05f0c5c9844e",
    "accept": "*/*",
    "origin": "chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop",
    "sec-fetch-site": "none",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/v1.0/artistsDtls",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/v1.0/artistsDtls",
  "listenerPath": "/api/*",
  "relativePath": "/api/v1.0/artistsDtls",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/v1.0/artistsDtls",
  "rawRequestPath": "/api/v1.0/artistsDtls",
  "remoteAddress": "/127.0.0.1:53895",
  "requestPath": "/api/v1.0/artistsDtls"
}