#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/da84e2c3-020d-4123-94f3-0cc9e4242c45/ # 
title: artist-skills-api

securitySchemes:
  customSecurity: !include security-scheme/customSecurityScheme.raml

securedBy:
  - customSecurity
uses:
  artistResType: libraries/artist-resource-type.raml
  

/v1.0/artistsDtls:
  type: {artistResType.collection: {exampleReference1: !include examples/artistDtls.json, exampleReference2: !include examples/artistDtls.json,exampleReference3: !include examples/artistResp.json}}
  get:
    queryParameters:
      artistName:
        type: string
        example: "Aashika"
        required: false
  post: 
  /{artistName}:
    type: {artistResType.collection: {exampleReference1: !include examples/artistDtls.json}}
    get: